services:

   backend:
    image: ghcr.io/mrtuxcoder/lanbox-server:latest
    container_name: backend-api
    restart: unless-stopped
    networks:
      - lanbox-network
    volumes:
      - "${STORAGE_PATH}:/app/storage"
    # Match these IDs to the owner of ${STORAGE_PATH} on the host.
    user: "${PUID}:${PGID}"


   frontend:
    image: ghcr.io/mrtuxcoder/lanbox-client:latest
    container_name: frontend-app
    restart: unless-stopped
    networks:
      - lanbox-network
    ports:
      - "80:80"
      
    depends_on:
      - backend


networks:
  lanbox-network:
    driver: bridge

  
