name: LANBox CI/CD
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  PORT_BACKEND: ${{ secrets.PORT }}
  PUID: ${{ secrets.PUID }}
  PGID: ${{ secrets.PGID }}
  STORAGE_PATH: ${{ secrets.STORAGE_PATH }}

jobs:
  lint:
    name: Lint server and client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 22
            cache: npm
            cache-dependency-path: |
                client/package-lock.json
                server/package-lock.json

      - name: Install client dependencies
        working-directory: client
        run: npm ci

      - name: Install server dependencies
        working-directory: server
        run: npm ci

      - name: Lint client
        working-directory: client
        run: npm run lint

      - name: Lint server
        working-directory: server
        run: npm run lint

  test:
    name: Test server
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json

      - name: Install server dependencies
        working-directory: server
        run: npm ci

      - name: Run server tests
        working-directory: server
        run: npm test
        



        

      